### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by mustafaakin** [dylanmei/docker-zeppelin#1]
```
mustafa@server2:~$ docker pull dylanmei/zeppelin:master
Pulling repository dylanmei/zeppelin
61173ef3d921: Download complete
9faf01c9b0ef: Download complete
61e9c91c4f08: Download complete
d8890db84ffe: Download complete
96bb93e0574c: Download complete
629d143832fc: Download complete
768b62b62588: Download complete
475a461d7f91: Download complete
30d86da000d2: Download complete
2b42fc5469cd: Download complete
0783b90231de: Download complete
949c04a01814: Download complete
33a6341d7de2: Download complete
338eff7c5eb2: Download complete
01077eb49d6a: Download complete
a768dd47f94e: Download complete
4505a86bd2e0: Download complete
1c3e1a20f0c2: Download complete
9f8d134e626a: Download complete
c5735ed7f212: Download complete
54646cd1dfa4: Download complete
mustafa@server2:~$ docker run --name zeppelin -p 8080:8080 -p 8081:8081 dylanmei/zeppelin:master
Log dir doesn't exist, create /zeppelin/logs
Pid dir doesn't exist, create /zeppelin/run
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Error: Could not find or load main class org.apache.zeppelin.server.ZeppelinServer
```

**Comment by dylanmei** [comment]
Hello!

Use `dylanmei/zeppelin:latest` unless you want to customize the image.

The README here on github is correct. If you can from hub.docker.com, then the README there is wrong and I'll see about updating it today.

**Comment by mustafaakin** [comment]
Oh, I see, thanks, now runs. But howeveri n the tutorial it says interpreter not found when I try to run them.

**Comment by dylanmei** [comment]
Have you setup the interpreter?
![Imgur](http://i.imgur.com/1J8nsfn.png)

**Comment by mustafaakin** [comment]
I'm sorry, I did not. Really being stupid today :stuck_out_tongue: 

Thanks, it now works perfectly!

**Comment by dylanmei** [comment]
Great! Good luck.

**Comment by sylvinho81** [comment]
Hi @dylanmei  I downloaded your repository from Github because I want to modify it in order to save the notebooks in Amazon S3. 
But when I try to run the docker container I get the same error than @mustafaakin:

Error: Could not find or load main class org.apache.zeppelin.server.ZeppelinServer

Could you provide me help with this?

Thanks
