### ISSUE TITLE
Fail to pull this image

### ISSUE THREAD

**Issue by harryprince** [dylanmei/docker-zeppelin#11]
Pulling repository dylanmei/zeppelin 

0e7e792c4b27: Download complete                                                                                   
a3ed95caeb02: Download complete                                                                                   
cff572cb15e9: Download failed                                                                                     
4619012a2e7f: Download failed                                                                                     
66ec4055137d: Download failed                                                                                     
325cefd4f6b7: Download failed                                                                                     
100836b3b4e1: Download failed                                                                                     
b9b71a4300e1: Download failed                                                                                     
41b8a6b77a2e: Download failed                                                                                     

Something wrong happend, fallback to docker native
Pulling repository docker.io/dylanmei/zeppelin
Failed, error info Get https://registry-1.docker.io/v1/repositories/dylanmei/zeppelin/tags/latest: net/http: TLS handshake timeout

**Comment by dylanmei** [comment]
It's a large image, hosted by hub.docker.com. Try again?
