### ISSUE TITLE
Load maven-dependencies

### ISSUE THREAD

**Issue by BirgerK** [dylanmei/docker-zeppelin#13]
I really enjoy your project. But how do you add jar-dependencies without maven? It seems like the image does not have any maven-installation.

What's your workflow for adding a jar-file?

**Comment by dylanmei** [comment]
Hello. I hope I understand your question.

The first way is through Zeppelin UI, which is what I usually do: http://zeppelin.apache.org/docs/0.7.0-SNAPSHOT/manual/dependencymanagement.html

The second way is to set `SPARK_SUBMIT_OPTIONS` when starting Zeppelin.
- There's an example in this project: https://github.com/dylanmei/docker-zeppelin/blob/master/examples/elasticsearch/docker-compose.yml#L14
- The [Advanced Dependency Management](https://spark.apache.org/docs/latest/submitting-applications.html) part of the Spark docs describe the `--jars` and `--repositories` options in more detail.

**Comment by BirgerK** [comment]
Hi, thanks for your answer.

I did already add the maven-dependency to the interpreter-config. If I do this on my local non-docker instance Maven downloads the dependency and it's then available to the Zeppelin Interpreter.

But in this docker-image this does not work. Does it work on your instance?

**Comment by dylanmei** [comment]
Maven isn't required in order to download dependencies from places like Maven central.

Spark simply uses HTTP to get these dependencies when `spark-submit` is invoked by Zeppelin. Similarly, you could use CURL:

```
curl -O http://central.maven.org/maven2/mysql/mysql-connector-java/6.0.3/mysql-connector-java-6.0.4.jar
```
As an exercise, please try running `spark-shell` via Docker and passing your dependency as an argument:

```
docker run --rm -it -w /usr/spark-2.0.0 dylanmei/zeppelin bin/spark-shell --packages "mysql:mysql-connector-java:6.0.3"
```
You should see a message indicating that Spark is downloading the `mysql-connector` package:

```
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
	found mysql#mysql-connector-java;6.0.3 in central
downloading https://repo1.maven.org/maven2/mysql/mysql-connector-java/6.0.3/mysql-connector-java-6.0.3.jar ...
	[SUCCESSFUL ] mysql#mysql-connector-java;6.0.3!mysql-connector-java.jar (495ms)
```

So you can see, Spark doesn't need Maven.

Recently, [Zeppelin had trouble passing dependency request information down to Spark](https://github.com/apache/zeppelin/pull/1366). This was fixed about two weeks ago. Is you Docker image of `dylanmei/zeppelin` newer than two weeks ago?

When I run `docker images | grep zeppelin` this is what I get:

```
dylanmei/zeppelin                                                                0.7.0                                                             db6c47e30888        2 weeks ago         1.695 GB
dylanmei/zeppelin                                                                latest                                                            db6c47e30888        2 weeks ago         1.695 GB
dylanmei/zeppelin                                                                0.6.0                                                             e058d6711b33        3 months ago        1.637 GB
```

**Comment by BirgerK** [comment]
My image is from yesterday, so yes, it's up to date.

And yes, if I run your spark-dependency-command, it's downloading the jar. Seems like that isn't the problem. But why does it even throw the exception?

**Comment by dylanmei** [comment]
Thanks for being patient with me. I see your issue now, I believe it's related to this issue in Zeppelin: https://github.com/apache/zeppelin/pull/1380

That is recently fixed. I will rebuild this image with this commit and write a message here when it's updated.

**Comment by dylanmei** [comment]
Both `docker pull dylanmei/zeppelin:latest` and `docker pull dylanmei/zeppelin:0.7.0` will pull down new version. Give it a try!

**Comment by BirgerK** [comment]
Now everything is fine. Thank you!
