### ISSUE TITLE
0.7.0 Container is Basically Unusable

### ISSUE THREAD

**Issue by jramapuram** [dylanmei/docker-zeppelin#14]
This issue is present:

https://issues.apache.org/jira/browse/SPARK-17103

**Comment by dylanmei** [comment]
This is a Spark problem. You can work around this in two ways:

1. Don't bother with a classes; inlining everything is quite common with notebook systems

```
%spark
import java.io.File
val f = new File(".")
> f: java.io.File = .
```

2. Embed your import, as discussed in the issue you referenced.

```
%spark
class Test {
  import java.io.File
  val f=new File(".")
}
> defined class Test
```

**Comment by jramapuram** [comment]
As per the JIRA ticket it looks like they have fixed it though, wonder if the changes could be pulled in?

Yea, using the fully qualified name does resolve it.  Thanks!

**Comment by dylanmei** [comment]
It looks like they "Resolved" it by marking it as a `Duplicate` of this issue: https://issues.apache.org/jira/browse/SPARK-14146
