### ISSUE TITLE
Zeppelin only supports Java7

### ISSUE THREAD

**Issue by BirgerK** [dylanmei/docker-zeppelin#16]
Zeppelin currently only supports Java7. If using Java8 some problems can occure...

![screen shot 2016-09-17 at 14 01 20](https://cloud.githubusercontent.com/assets/3985597/18608079/513ec8fe-7cdf-11e6-831c-9fc15cda922a.png)

Seems like this image has the JAVA_HOME env-variable set to a Java8-installation under `/usr/jdk1.8.0_92`. Can this be changed?

As base-image is a spark-image used. That's not necessary, because Zeppelin delivers it's own embedded Spark. You could change the base-image to a simple OpenJDK-8-JDK image. By this would be some space and complexity saved.

**Comment by dylanmei** [comment]
In production deployments where I work we use this Zeppelin image along with the `gettyimages/spark` image for distributed Spark executors. So I'm content using `gettyimages/spark` as the `FROM` container for the `Dockerfile`.

If using a different Java makes things better and smaller, I'd like to do that there.

Finally, the embedded Spark may be convenient for local deployments, but it is perfectly normal to "Bring your own Spark" to Zeppelin: http://zeppelin.apache.org/docs/0.7.0-SNAPSHOT/interpreter/spark.html#1-export-spark_home

**Comment by BirgerK** [comment]
I understand. How about to set the `SPARK_HOME`-variable to the given Spark-Installation so Zeppelin won't use it's internal Spark? I think this would be the clean way for the existing image.

**Comment by BirgerK** [comment]
Well yeah... I don't know. If it works, then it works. ;)
