### ISSUE TITLE
Yaml issue

### ISSUE THREAD

**Issue by blitzd** [dylanmei/docker-zeppelin#2]
I'm getting an error upon trying to run the docker-compose up command:

yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 26, column 23

I don't see anything unusual on that line. I updated pyaml/PyYAML, tried formatting the yml file so that there were spaces after every single colon, still no dice. Any ideas?

**Comment by dylanmei** [comment]
Thanks for pointing that out. I had left the yaml in a bad state. Try getting latest.

**Comment by blitzd** [comment]
Thanks, that seems to have done the trick! I do have one other issue now, but I'll put that in a separate post.
