### ISSUE TITLE
%spark.pyspark not working in latest

### ISSUE THREAD

**Issue by carlos-eduardo-gb** [dylanmei/docker-zeppelin#21]
when i'm running %spark.pyspark i got this message:

```
%spark.pyspark
spark
python process not runningorg.apache.zeppelin.interpreter.util.InterpreterOutputStream@ed6be98
```

but if i run
```
%spark
spark
res3: org.apache.spark.sql.SparkSession = org.apache.spark.sql.SparkSession@412284b5

```
any idea of why this is happening?

Thanks!

**Comment by egorpushkin** [comment]
Just notices that as well. It appears so that Spark interpreter is configure with `zeppelin.pyspark.python:python` by default. And `python` is not available within the container. Changing it to `python3` in interpreter settings resolves the issue. 

@dylanmei FYI

**Comment by egorpushkin** [comment]
Actually it looks like python is being referred to from other places as well (spark itself at least). My local workaround (this also eliminates the need to the hack i mentioned above): 

```
FROM dylanmei/zeppelin:latest
RUN cp /usr/bin/python3 /usr/bin/python
```
(using aliasing is a bit trickier option)

Correct solution would involve configuring Spark and Zeppelin properly.

**Comment by dylanmei** [comment]
You can set the `zeppelin.python` var to `python3` in the interpreter settings.

For Zeppelin 0.7.1 image `python` has been aliased to `python3` in this commit 0d75e9482bd6fbf1f90100a000c00b166e3dd279
