### ISSUE TITLE
%sql throwing java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by blitzd** [dylanmei/docker-zeppelin#3]
This only happens when I run in the docker-compose method, if I run a single instance everything works fine. I don't see any other error message, but basically all the charts at the end of the tutorial throw this when run with the docker-compose, yet don't using the same docker images when run one-off.

**Comment by dylanmei** [comment]
That's interesting, thanks for the heads up. I will repro this later today/tomorrow.

**Comment by dylanmei** [comment]
This is addressed in 2fb77afb0fcd3c615e712e79478c8852559faf27
Let me know how that works out. Thanks :)

**Comment by blitzd** [comment]
Works a charm, thanks!
