### ISSUE TITLE
Can not run 

### ISSUE THREAD

**Issue by sylvinho81** [dylanmei/docker-zeppelin#4]
Hi @dylanmei I downloaded your repository from Github because I want to modify it in order to save the notebooks in Amazon S3. 
But when I try to run the docker container I get the same error than @mustafaakin:

Error: Could not find or load main class org.apache.zeppelin.server.ZeppelinServer

Could you provide me help with this?

Thanks

**Comment by dylanmei** [comment]
Hello @sylvinho81, Are using

    docker pull dylanmei/zeppelin:master

or

    docker pull dylanmei/zeppelin:latest

If you're just getting started or aren't very familiar with docker, you want the image tagged "latest".

**Comment by sylvinho81** [comment]
Hello, 

Yep, I tried it and it works. But I was trying to clone your repository for adding some modifications and create my own docker container. 
I am doing git clone https://github.com/dylanmei/docker-zeppelin.git for getting it. Should I do something different?
Here is my docker repository: https://hub.docker.com/r/sylvinho81/zeppelin/

Thanks

**Comment by dylanmei** [comment]
Have you read this part of the README? [github.com/dylanmei/docker-zeppelin#customize](https://github.com/dylanmei/docker-zeppelin#customize)

Read that first and come back here.

If what you want is an automated build in docker hub then Instead of forking this repo:
1. create a repo with your own install.sh
2. create a Dockerfile with only one line: `FROM dylanmei/zeppelin:master`
3. finally run `docker build -t my-zeppelin .`

**Comment by sylvinho81** [comment]
Thanks @dylanmei. I am gonna try it and I will let you know if it works for me.

**Comment by dylanmei** [comment]
Great! Good luck.

**Comment by sylvinho81** [comment]
Hi @dylanmei. I tried to follow your steps and everything seems to work fine. But now I am having problems in the last step related to the' mvn clean package' inside  incubator-zeppelin. A problem with karma: https://github.com/apache/incubator-zeppelin/pull/390

Just wondering why when I try to use your docker container it works. It seem that when you built the docker container you were using a previous version of incubator-zeppelin.

**Comment by sylvinho81** [comment]
Hi @dylanmei, finally I could solve that problem. Following your steps I created my own docker image to install Zeppelin. 

Thanks!!! I appreciate a lot your help.

**Comment by dylanmei** [comment]
That's good news! :)

**Comment by mattsahn** [comment]
Thanks for the detailed instructions. I am able to get Zeppelin up and running on Google Compute Engine and I used the docker-compose command and config to start a cluster as you described. I can access both the spark master and zeppelin web pages. However, Zeppelin shows as "Disconnected" so I can't actually do anything with it or create a new note.
Any suggestions on how to investigate/debug this connection issue? Below is the tail of the docker-compose output:

```
master_1   | 15/11/16 16:49:37 INFO AbstractConnector: Started SelectChannelConnector@master:6066
master_1   | 15/11/16 16:49:37 INFO Utils: Successfully started service on port 6066.
master_1   | 15/11/16 16:49:37 INFO StandaloneRestServer: Started REST server for submitting applications on port 6066
master_1   | 15/11/16 16:49:37 INFO Master: Starting Spark master at spark://master:7077
master_1   | 15/11/16 16:49:37 INFO Master: Running Spark version 1.3.1
master_1   | 15/11/16 16:49:37 INFO Server: jetty-8.y.z-SNAPSHOT
master_1   | 15/11/16 16:49:37 INFO AbstractConnector: Started SelectChannelConnector@0.0.0.0:8080
master_1   | 15/11/16 16:49:37 INFO Utils: Successfully started service 'MasterUI' on port 8080.
master_1   | 15/11/16 16:49:37 INFO MasterWebUI: Started MasterWebUI at http://master:8080
worker_1   | 15/11/16 16:49:38 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkWorker@worker:8881]
worker_1   | 15/11/16 16:49:38 INFO Remoting: Remoting now listens on addresses: [akka.tcp://sparkWorker@worker:8881]
worker_1   | 15/11/16 16:49:38 INFO Utils: Successfully started service 'sparkWorker' on port 8881.
zeppelin_1 | Nov 16, 2015 4:49:38 PM com.sun.jersey.api.core.PackagesResourceConfig init
zeppelin_1 | INFO: Scanning for root resource and provider classes in the packages:
zeppelin_1 |   org.apache.zeppelin.rest
zeppelin_1 |   com.wordnik.swagger.jersey.listing
worker_1   | 15/11/16 16:49:38 INFO Worker: Starting Spark worker worker:8881 with 1 cores, 1024.0 MB RAM
worker_1   | 15/11/16 16:49:38 INFO Worker: Running Spark version 1.3.1
worker_1   | 15/11/16 16:49:38 INFO Worker: Spark home: /usr/spark
master_1   | 15/11/16 16:49:38 INFO Master: I have been elected leader! New state: ALIVE
zeppelin_1 | Nov 16, 2015 4:49:38 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
zeppelin_1 | INFO: Root resource classes found:
zeppelin_1 |   class org.apache.zeppelin.rest.NotebookRestApi
zeppelin_1 |   class org.apache.zeppelin.rest.ZeppelinRestApi
zeppelin_1 |   class org.apache.zeppelin.rest.InterpreterRestApi
zeppelin_1 |   class com.wordnik.swagger.jersey.listing.ApiListingResourceJSON
zeppelin_1 | Nov 16, 2015 4:49:38 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
zeppelin_1 | INFO: Provider classes found:
zeppelin_1 |   class com.wordnik.swagger.jersey.listing.JerseyApiDeclarationProvider
zeppelin_1 |   class com.wordnik.swagger.jersey.listing.JerseyResourceListingProvider
worker_1   | 15/11/16 16:49:38 INFO Server: jetty-8.y.z-SNAPSHOT
zeppelin_1 | Nov 16, 2015 4:49:38 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
zeppelin_1 | INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
zeppelin_1 | Nov 16, 2015 4:49:38 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
zeppelin_1 | INFO: Adding the following classes declared in META-INF/services/jersey-server-components to the resource configuration:
zeppelin_1 |   class org.atmosphere.jersey.AtmosphereResourceConfigurator
worker_1   | 15/11/16 16:49:38 INFO AbstractConnector: Started SelectChannelConnector@0.0.0.0:8081
worker_1   | 15/11/16 16:49:39 INFO Utils: Successfully started service 'WorkerUI' on port 8081.
worker_1   | 15/11/16 16:49:39 INFO WorkerWebUI: Started WorkerWebUI at http://worker:8081
worker_1   | 15/11/16 16:49:39 INFO Worker: Connecting to master akka.tcp://sparkMaster@master:7077/user/Master...
master_1   | 15/11/16 16:49:40 INFO Master: Registering worker worker:8881 with 1 cores, 1024.0 MB RAM
worker_1   | 15/11/16 16:49:40 INFO Worker: Successfully registered with master spark://master:7077
zeppelin_1 | Nov 16, 2015 4:49:40 PM com.sun.jersey.spi.inject.Errors processErrorMessages
zeppelin_1 | WARNING: The following warnings have been detected with resource and/or provider classes:
zeppelin_1 |   WARNING: A HTTP GET method, public javax.ws.rs.core.Response org.apache.zeppelin.rest.InterpreterRestApi.listInterpreter(java.lang.Str
ing), should not consume any entity.
```

**Comment by dylanmei** [comment]
Nothing in that output stands out as a problem. Have you started the Spark interpreter?

![zepint](https://cloud.githubusercontent.com/assets/109874/11189037/aad1b5fe-8c42-11e5-893e-68d889229fd6.png)

**Comment by mattsahn** [comment]
Figured it out.  Firewall issue. Port 8090 was open in my firewall, which was letting me connect to the Zeppelin web GUI, but port 8091 was not open. 8091 is used for websocket connection. Adding that and relaunching has it connecting and working now. thanks for your prompt reply.

**Comment by dylanmei** [comment]
That's good news. :+1:
