### ISSUE TITLE
Could not find or load main class org.apache.zeppelin.server.ZeppelinServer

### ISSUE THREAD

**Issue by Liu-Huaqing** [dylanmei/docker-zeppelin#5]
Hi dylanmei,
I pull the image dylanmei/zeppelin:latest from daocloud repository which is the mirror of docker hub in china. And I try to use this command to run it:  
`
docker run --name zeppelin -p 8080:8080 -p 8081:8081 dylanmei/zeppelin:latest
`
But it could throw this error: 

Log dir doesn't exist, create /zeppelin/logs
Pid dir doesn't exist, create /zeppelin/run
Error: Could not find or load main class org.apache.zeppelin.server.ZeppelinServer

**Comment by dylanmei** [comment]
I can confirm, I get the same error from hub.docker.com. I will try to rebuild there. If I still have problem I will have to dig deeper.

Thank you for your issue. :)

**Comment by Liu-Huaqing** [comment]
Thanks for your quick action and your image. :). I will update this image when you resolve this issue. :)

**Comment by dylanmei** [comment]
The rebuild works for me. Can you verify?

**Comment by dylanmei** [comment]
I believe this is now cleared up.
